### ISSUE TITLE
Redis Queue Driver disable Continuous debug log in console

### ISSUE THREAD

**Issue by binarysid** [swift-server/RediStack#87]
I have configured RedisQueue Driver for my vapor project. While running the app the console becomes flooded with continuous debug log from the driver connection. I can barely see the other logs. Is there any way to disable the RedisQueue driver connection log? Screenshot of my console is attached. (Notes: I am running the service with docker compose)
![Screenshot 2023-08-06 at 4 15 33 PM](https://github.com/swift-server/RediStack/assets/8467088/d8a144e6-a0f8-4a26-8801-677666735c67)

**Comment by Joannis** [comment]
Hello @binarysid , I discussed the topic with @fabianfett . While we agree that it's verbose, this is expected behaviour when logging on a debug log level.

The current behaviour is _mostly_ inline with the [SSWG Log Level guide](https://www.swift.org/server/guides/libraries/log-levels.html). However, as a results of yours logs we _do_ think that the statement for finding connections in a pool should be a `trace` instead.

The solution is to increase the logging level to `info` instead.
